import { type ContentRecord } from '@d2xyz/cms';

export const tags = {
  tags: [
    'fantasy',
    'RPG',
    'gaming',
    'characters',
    'animals',
    'monsters',
    'companions',
    'pets',
    'fighters',
    'scholars',
    'engineers',
    'armor',
    'ambients',
    'landscapes',
    'scenes',
    'abstract',
  ],
};

export const collections: ContentRecord = {
  'the-cleric': {
    title: 'The Cleric',
    date: new Date('11-01-2022').toISOString(),
    img: 'https://cdn.midjourney.com/c50954b6-a2c9-4e54-9ea9-14242bfdf9fc/grid_0.png',
    tags: ['fantasy', 'RPG', 'characters', 'scholars'],
    link: '/gallery/the-cleric',
    actions: [
      ['4K Resolution', 'https://ricardojrmcom.gumroad.com/l/the-cleric-4k'],
    ],
    items: {
      1: {
        title: 'The Cleric #1',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/c50954b6-a2c9-4e54-9ea9-14242bfdf9fc/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'male'],
        link: '/gallery/the-cleric/1',
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      2: {
        title: 'The Cleric #2',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/5ef55d1a-a2bd-4f36-a4eb-7c081bec7857/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'female'],
        link: '/gallery/the-cleric/2',
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      3: {
        title: 'The Cleric #3',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/a8228016-4230-48ff-a4f4-7690d6f3c9f5/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'male'],
        link: '/gallery/the-cleric/3',
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      4: {
        title: 'The Cleric #4',
        link: '/gallery/the-cleric/4',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/109f3abc-abb5-4776-8439-6b8979c54253/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'female'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      5: {
        title: 'The Cleric #5',
        link: '/gallery/the-cleric/5',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/23e3eea9-88ee-4487-a056-04f4c917fc6d/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'male'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      6: {
        title: 'The Cleric #6',
        link: '/gallery/the-cleric/6',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/bbf41fee-adb2-4a8f-8a46-5daca24d3d73/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'female'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      7: {
        title: 'The Cleric #7',
        link: '/gallery/the-cleric/7',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/f900873b-58e9-49f3-aad6-d85b2f8a98b5/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'male'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      8: {
        title: 'The Cleric #8',
        link: '/gallery/the-cleric/8',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/3d049b66-8ea2-433a-a592-9f94f0a2f156/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'female'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      9: {
        title: 'The Cleric #9',
        link: '/gallery/the-cleric/9',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/dea06034-1300-4168-9d26-e43052513462/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'male'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      10: {
        title: 'The Cleric #10',
        link: '/gallery/the-cleric/10',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/f4427e4a-b824-4520-b3b0-0d7b90b5570c/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'female'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      11: {
        title: 'The Cleric #11',
        link: '/gallery/the-cleric/11',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/434c9edc-ad7e-4373-8de0-bbd207820cc9/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'male'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      12: {
        title: 'The Cleric #12',
        link: '/gallery/the-cleric/12',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/c866d83d-8c0b-4f0b-ac84-67cc552b2b1f/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'female'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      13: {
        title: 'The Cleric #13',
        link: '/gallery/the-cleric/13',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/d9560fcf-3565-4aa2-8483-54c7ccee83e8/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'male'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      14: {
        title: 'The Cleric #14',
        link: '/gallery/the-cleric/14',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/2a1362c4-5c84-434f-a360-0b3d3ecf6c20/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'female'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      15: {
        title: 'The Cleric #15',
        link: '/gallery/the-cleric/15',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/a34dc53e-093a-4dc2-a5dc-313d28c73b82/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'male'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      16: {
        title: 'The Cleric #16',
        link: '/gallery/the-cleric/16',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/092ce123-55d1-4f9e-90d0-1ccddd488507/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'female'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      17: {
        title: 'The Cleric #17',
        link: '/gallery/the-cleric/17',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/d5019d24-1aab-46fc-ae49-6383ae65fc3a/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'male'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      18: {
        title: 'The Cleric #18',
        link: '/gallery/the-cleric/18',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/a907315b-ac89-44a6-89b3-b0ec00b81774/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'female'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      19: {
        title: 'The Cleric #19',
        link: '/gallery/the-cleric/19',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/37bd0d5e-19e2-4785-9c9d-b6224fe336a1/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'male'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      20: {
        title: 'The Cleric #20',
        link: '/gallery/the-cleric/20',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/b60e202e-5052-4ff3-8c3f-3c580a5a36bf/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'female'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      21: {
        title: 'The Cleric #21',
        link: '/gallery/the-cleric/21',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/43fab3ff-ec97-4c0c-8e41-15827098d3c8/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'male'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      22: {
        title: 'The Cleric #22',
        link: '/gallery/the-cleric/22',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/f032b1c0-86d5-451e-afb5-ac5ffc999af3/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'female'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      23: {
        title: 'The Cleric #23',
        link: '/gallery/the-cleric/23',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/47858116-828e-4fcf-85b6-2b93cfe1c0d5/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'male'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      24: {
        title: 'The Cleric #24',
        link: '/gallery/the-cleric/24',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/d867bf74-a4a3-4308-b4a3-3837fa801237/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'female'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      25: {
        title: 'The Cleric #25',
        link: '/gallery/the-cleric/25',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/7a22138a-6ed4-4c65-b313-de80e8e61961/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'male'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      26: {
        title: 'The Cleric #26',
        link: '/gallery/the-cleric/26',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/1f09a536-dcee-470d-a35e-ba71ce2d98e1/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'female'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      27: {
        title: 'The Cleric #27',
        link: '/gallery/the-cleric/27',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/5a3dd3fc-51a4-42f8-9c1f-e536e151442f/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'male'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      28: {
        title: 'The Cleric #28',
        link: '/gallery/the-cleric/28',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/287e358d-fa51-4850-94f0-8adaeb723e63/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'female'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      29: {
        title: 'The Cleric #29',
        link: '/gallery/the-cleric/29',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/20fb27f7-c802-4f85-95d7-76e780466466/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'male'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      30: {
        title: 'The Cleric #30',
        link: '/gallery/the-cleric/30',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/ca4a3f7e-9e08-4e2f-92f2-1bbbb2afe4e7/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'female'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      31: {
        title: 'The Cleric #31',
        link: '/gallery/the-cleric/31',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/b52600a4-edc7-4e88-87aa-e61c03552735/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'male'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      32: {
        title: 'The Cleric #32',
        link: '/gallery/the-cleric/32',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/b3832a9f-6c54-4f88-97b6-5aa99389df71/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'female'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      33: {
        title: 'The Cleric #33',
        link: '/gallery/the-cleric/33',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/0717e4b4-0c9f-41ef-939b-dead9d66cf75/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'male'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
      34: {
        title: 'The Cleric #34',
        link: '/gallery/the-cleric/34',
        date: new Date('11-01-2022').toISOString(),
        img: 'https://cdn.midjourney.com/8d4889d3-1617-4962-b243-4f1a30c04a57/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'female'],
        actions: [
          [
            '4K Resolution',
            'https://ricardojrmcom.gumroad.com/l/the-cleric-4k',
          ],
        ],
      },
    },
  },
  'the-paladin': {
    title: 'The Paladin',
    link: '/gallery/the-paladin',
    date: new Date('11-02-2022').toISOString(),
    img: 'https://cdn.midjourney.com/325c5f2e-7ce3-444c-b4ed-25189f7fe277/grid_0.png',
    tags: ['fantasy', 'RPG', 'characters', 'armor'],
    items: {
      1: {
        title: 'The Paladin #1',
        link: '/gallery/the-paladin/1',
        date: new Date('11-02-2022').toISOString(),
        img: 'https://cdn.midjourney.com/325c5f2e-7ce3-444c-b4ed-25189f7fe277/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'armor', 'male'],
      },
      2: {
        title: 'The Paladin #2',
        link: '/gallery/the-paladin/2',
        date: new Date('11-02-2022').toISOString(),
        img: 'https://cdn.midjourney.com/ab7a5424-06c9-45f5-946f-45fb42f9d34b/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'armor', 'male'],
      },
      3: {
        title: 'The Paladin #3',
        link: '/gallery/the-paladin/3',
        date: new Date('11-02-2022').toISOString(),
        img: 'https://cdn.midjourney.com/13ae986d-f314-491b-b77c-1e7b587387b7/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'armor', 'male'],
      },
      4: {
        title: 'The Paladin #4',
        link: '/gallery/the-paladin/4',
        date: new Date('11-02-2022').toISOString(),
        img: 'https://cdn.midjourney.com/bbf490eb-31d9-4c44-98d6-a68111a3365f/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'armor', 'male'],
      },
      5: {
        title: 'The Paladin #5',
        link: '/gallery/the-paladin/5',
        date: new Date('11-02-2022').toISOString(),
        img: 'https://cdn.midjourney.com/18bfb49b-b076-4f7f-a560-721b0e5c19d0/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'armor', 'female'],
      },
      6: {
        title: 'The Paladin #6',
        link: '/gallery/the-paladin/6',
        date: new Date('11-02-2022').toISOString(),
        img: 'https://cdn.midjourney.com/2f62d851-98b3-4c0e-9f7e-19f3da3be50f/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'armor', 'female'],
      },
      7: {
        title: 'The Paladin #7',
        link: '/gallery/the-paladin/7',
        date: new Date('11-02-2022').toISOString(),
        img: 'https://cdn.midjourney.com/7f1e58c5-f0ad-4dcb-9483-6ced6928c337/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'armor', 'female'],
      },
      8: {
        title: 'The Paladin #8',
        link: '/gallery/the-paladin/8',
        date: new Date('11-02-2022').toISOString(),
        img: 'https://cdn.midjourney.com/5b168b4f-9b79-4f4a-8d7e-c8189dee9b6a/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'armor', 'female'],
      },
      9: {
        title: 'The Paladin #9',
        link: '/gallery/the-paladin/9',
        date: new Date('11-02-2022').toISOString(),
        img: 'https://cdn.midjourney.com/b4fd1597-77e8-42dd-b4ed-ecbc989c04af/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'armor', 'male'],
      },
      10: {
        title: 'The Paladin #10',
        link: '/gallery/the-paladin/10',
        date: new Date('11-02-2022').toISOString(),
        img: 'https://cdn.midjourney.com/080fddf7-10ae-4229-92f0-b1422104f62b/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'armor', 'male'],
      },
      11: {
        title: 'The Paladin #11',
        link: '/gallery/the-paladin/11',
        date: new Date('11-02-2022').toISOString(),
        img: 'https://cdn.midjourney.com/55d5276c-5dea-4cd4-b74a-96f30215bf60/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'armor', 'male'],
      },
      12: {
        title: 'The Paladin #12',
        link: '/gallery/the-paladin/12',
        date: new Date('11-02-2022').toISOString(),
        img: 'https://cdn.midjourney.com/9d3f5812-ef2d-47a8-a4dd-2a2f92f01a28/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'armor', 'male'],
      },
      13: {
        title: 'The Paladin #13',
        link: '/gallery/the-paladin/13',
        date: new Date('11-02-2022').toISOString(),
        img: 'https://cdn.midjourney.com/5eeaabf9-1b06-4299-b715-c94fc3a61ffa/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'armor', 'female'],
      },
      14: {
        title: 'The Paladin #14',
        link: '/gallery/the-paladin/14',
        date: new Date('11-02-2022').toISOString(),
        img: 'https://cdn.midjourney.com/8d239d11-f93a-4fe0-8f27-2e780fbdb355/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'armor', 'female'],
      },
      15: {
        title: 'The Paladin #15',
        link: '/gallery/the-paladin/15',
        date: new Date('11-02-2022').toISOString(),
        img: 'https://cdn.midjourney.com/097b9283-96cb-4e6e-8ac6-6e0836a681c1/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'armor', 'female'],
      },
      16: {
        title: 'The Paladin #16',
        link: '/gallery/the-paladin/16',
        date: new Date('11-02-2022').toISOString(),
        img: 'https://cdn.midjourney.com/635645f0-3844-40c5-adca-c4c9f39d7dc9/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'armor', 'female'],
      },
      17: {
        title: 'The Paladin #17',
        link: '/gallery/the-paladin/17',
        date: new Date('11-02-2022').toISOString(),
        img: 'https://cdn.midjourney.com/95005b36-e5af-444a-a1eb-14de17e8f381/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'armor', 'male'],
      },
      18: {
        title: 'The Paladin #18',
        link: '/gallery/the-paladin/18',
        date: new Date('11-02-2022').toISOString(),
        img: 'https://cdn.midjourney.com/ce7f7411-2762-49af-93e8-9e28c2dcb317/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'armor', 'female'],
      },
      19: {
        title: 'The Paladin #19',
        link: '/gallery/the-paladin/19',
        date: new Date('11-02-2022').toISOString(),
        img: 'https://cdn.midjourney.com/dd3ace55-3dfc-4d8f-8a5e-a133798f48e8/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'armor', 'female'],
      },
      20: {
        title: 'The Paladin #20',
        link: '/gallery/the-paladin/20',
        date: new Date('11-02-2022').toISOString(),
        img: 'https://cdn.midjourney.com/2bda1c23-6856-4f70-9cc7-55699a033db7/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'armor', 'female'],
      },
    },
  },
  'the-fighter': {
    title: 'The Fighter',
    link: '/gallery/the-fighter',
    date: new Date('11-03-2022').toISOString(),
    img: 'https://cdn.midjourney.com/5d19c34c-ef87-48c3-9470-6303ddcfc4d8/grid_0.png',
    tags: ['fantasy', 'RPG', 'characters', 'fighters'],
    items: {
      1: {
        title: 'The Fighter #1',
        link: '/gallery/the-fighter/1',
        date: new Date('11-03-2022').toISOString(),
        img: 'https://cdn.midjourney.com/5d19c34c-ef87-48c3-9470-6303ddcfc4d8/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'fighters', 'female'],
      },
      2: {
        title: 'The Fighter #2',
        link: '/gallery/the-fighter/2',
        date: new Date('11-03-2022').toISOString(),
        img: 'https://cdn.midjourney.com/787055bb-06e3-423c-bd43-507e73cc5e8f/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'fighters', 'male'],
      },
      3: {
        title: 'The Fighter #3',
        link: '/gallery/the-fighter/3',
        date: new Date('11-03-2022').toISOString(),
        img: 'https://cdn.midjourney.com/f9d6bafc-a659-454b-ad93-53d8c3597358/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'fighters', 'female'],
      },
      4: {
        title: 'The Fighter #4',
        link: '/gallery/the-fighter/4',
        date: new Date('11-03-2022').toISOString(),
        img: 'https://cdn.midjourney.com/eced7a64-7d2c-474a-93de-e8b2a58382a4/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'fighters', 'male'],
      },
      5: {
        title: 'The Fighter #5',
        link: '/gallery/the-fighter/5',
        date: new Date('11-03-2022').toISOString(),
        img: 'https://cdn.midjourney.com/9c45a088-d829-4e4c-b065-45d927f72fde/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'fighters', 'female'],
      },
      6: {
        title: 'The Fighter #6',
        link: '/gallery/the-fighter/6',
        date: new Date('11-03-2022').toISOString(),
        img: 'https://cdn.midjourney.com/62c01ac7-bdd4-4255-811f-ebe905a9cbe3/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'fighters', 'male'],
      },
      7: {
        title: 'The Fighter #7',
        link: '/gallery/the-fighter/7',
        date: new Date('11-03-2022').toISOString(),
        img: 'https://cdn.midjourney.com/4295919b-103e-4c3d-afed-cc6422affd3d/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'fighters', 'female'],
      },
      8: {
        title: 'The Fighter #8',
        link: '/gallery/the-fighter/8',
        date: new Date('11-03-2022').toISOString(),
        img: 'https://cdn.midjourney.com/6fef78f3-220b-4892-85e3-e031cf97e6e2/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'fighters', 'male'],
      },
      9: {
        title: 'The Fighter #9',
        link: '/gallery/the-fighter/9',
        date: new Date('11-03-2022').toISOString(),
        img: 'https://cdn.midjourney.com/9657cd78-d63c-4482-abda-56afefb306a8/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'fighters', 'female'],
      },
      10: {
        title: 'The Fighter #10',
        link: '/gallery/the-fighter/10',
        date: new Date('11-03-2022').toISOString(),
        img: 'https://cdn.midjourney.com/106fc97e-ce53-4b11-b5c1-aab8d197a29e/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'fighters', 'male'],
      },
      11: {
        title: 'The Fighter #11',
        link: '/gallery/the-fighter/11',
        date: new Date('11-03-2022').toISOString(),
        img: 'https://cdn.midjourney.com/e840f98c-5896-4e78-a2f6-685e05aa6060/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'fighters', 'female'],
      },
      12: {
        title: 'The Fighter #12',
        link: '/gallery/the-fighter/12',
        date: new Date('11-03-2022').toISOString(),
        img: 'https://cdn.midjourney.com/ca9e07db-bdaa-4b09-abd9-94a3886b5753/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'fighters', 'male'],
      },
      13: {
        title: 'The Fighter #13',
        link: '/gallery/the-fighter/13',
        date: new Date('11-03-2022').toISOString(),
        img: 'https://cdn.midjourney.com/4cb3952c-8f9d-4978-9db4-ec67884679a0/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'fighters', 'female'],
      },
      14: {
        title: 'The Fighter #14',
        link: '/gallery/the-fighter/14',
        date: new Date('11-03-2022').toISOString(),
        img: 'https://cdn.midjourney.com/5e8caf4f-e851-48ed-8a8d-d073b283ac5c/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'fighters', 'male'],
      },
      15: {
        title: 'The Fighter #15',
        link: '/gallery/the-fighter/15',
        date: new Date('11-03-2022').toISOString(),
        img: 'https://cdn.midjourney.com/9c45a088-d829-4e4c-b065-45d927f72fde/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'fighters', 'female'],
      },
      16: {
        title: 'The Fighter #16',
        link: '/gallery/the-fighter/16',
        date: new Date('11-03-2022').toISOString(),
        img: 'https://cdn.midjourney.com/19620b3b-de18-460e-8ac7-348e1328b262/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'fighters', 'male'],
      },
    },
  },
  'the-bard': {
    title: 'The Bard',
    link: '/gallery/the-bard',
    date: new Date('11-06-2022').toISOString(),
    img: 'https://cdn.midjourney.com/916bd56a-1c55-46f8-b767-002d3bf4e2bc/grid_0.png',
    tags: ['fantasy', 'RPG', 'characters', 'support', 'male'],
    items: {
      1: {
        title: 'The Bard #1',
        link: '/gallery/the-bard/1',
        date: new Date('11-06-2022').toISOString(),
        img: 'https://cdn.midjourney.com/916bd56a-1c55-46f8-b767-002d3bf4e2bc/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'support', 'male'],
      },
      2: {
        title: 'The Bard #2',
        link: '/gallery/the-bard/2',
        date: new Date('11-06-2022').toISOString(),
        img: 'https://cdn.midjourney.com/f3a67a5b-27cf-4921-ac63-2dc0096a91b1/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'support', 'animal'],
      },
      3: {
        title: 'The Bard #3',
        link: '/gallery/the-bard/3',
        date: new Date('11-06-2022').toISOString(),
        img: 'https://cdn.midjourney.com/3a3ca236-f2fd-4593-a967-3398fc6f9059/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'support', 'male'],
      },
      4: {
        title: 'The Bard #4',
        link: '/gallery/the-bard/4',
        date: new Date('11-06-2022').toISOString(),
        img: 'https://cdn.midjourney.com/9a035605-d9d6-47eb-9daa-fa67a08b491e/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'support', 'male'],
      },
      5: {
        title: 'The Bard #5',
        link: '/gallery/the-bard/5',
        date: new Date('11-06-2022').toISOString(),
        img: 'https://cdn.midjourney.com/25f03be9-3ab7-4fbd-9b48-90d2f24fe20a/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'support', 'male'],
      },
      6: {
        title: 'The Bard #6',
        link: '/gallery/the-bard/6',
        date: new Date('11-06-2022').toISOString(),
        img: 'https://cdn.midjourney.com/1fca4e7f-b578-4432-902d-f55abc0841a6/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'support', 'male'],
      },
      7: {
        title: 'The Bard #7',
        link: '/gallery/the-bard/7',
        date: new Date('11-06-2022').toISOString(),
        img: 'https://cdn.midjourney.com/514e7342-e22d-4c79-8f5a-e08716db3120/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'support', 'male'],
      },
      8: {
        title: 'The Bard #8',
        link: '/gallery/the-bard/8',
        date: new Date('11-06-2022').toISOString(),
        img: 'https://cdn.midjourney.com/f6571954-0ea8-4d3e-9cee-3d245cb813a0/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'support', 'male'],
      },
    },
  },
  'the-dancer': {
    title: 'The Dancer',
    link: '/gallery/the-dancer',
    date: new Date('11-05-2022').toISOString(),
    img: 'https://cdn.midjourney.com/e5d82375-64b0-4e4a-916d-cb8188e25321/grid_0.png',
    tags: ['fantasy', 'RPG', 'characters', 'support', 'female'],
    items: {
      1: {
        title: 'The Dancer #1',
        link: '/gallery/the-dancer/1',
        date: new Date('11-05-2022').toISOString(),
        img: 'https://cdn.midjourney.com/e5d82375-64b0-4e4a-916d-cb8188e25321/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'support', 'female'],
      },
      2: {
        title: 'The Dancer #2',
        link: '/gallery/the-dancer/2',
        date: new Date('11-05-2022').toISOString(),
        img: 'https://cdn.midjourney.com/70586807-24c8-4f92-aa93-91e7897fa7a1/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'support', 'female'],
      },
      3: {
        title: 'The Dancer #3',
        link: '/gallery/the-dancer/3',
        date: new Date('11-05-2022').toISOString(),
        img: 'https://cdn.midjourney.com/ab270317-cade-4efe-88f8-42f3715370b2/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'support', 'female'],
      },
      4: {
        title: 'The Dancer #4',
        link: '/gallery/the-dancer/4',
        date: new Date('11-05-2022').toISOString(),
        img: 'https://cdn.midjourney.com/204c8675-4f8b-4aa5-9cc4-e07898eb81a9/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'support', 'female'],
      },
      5: {
        title: 'The Dancer #5',
        link: '/gallery/the-dancer/5',
        date: new Date('11-05-2022').toISOString(),
        img: 'https://cdn.midjourney.com/b98db7e8-793b-4f65-9dbe-9a46e7659c65/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'support', 'female'],
      },
      6: {
        title: 'The Dancer #6',
        link: '/gallery/the-dancer/6',
        date: new Date('11-05-2022').toISOString(),
        img: 'https://cdn.midjourney.com/be785492-f4be-4eb4-bf0c-e9e9390dcccf/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'support', 'female'],
      },
      7: {
        title: 'The Dancer #7',
        link: '/gallery/the-dancer/7',
        date: new Date('11-05-2022').toISOString(),
        img: 'https://cdn.midjourney.com/4ea85217-e27c-4f3b-a464-9089c07cc268/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'support', 'female'],
      },
      8: {
        title: 'The Dancer #8',
        link: '/gallery/the-dancer/8',
        date: new Date('11-05-2022').toISOString(),
        img: 'https://cdn.midjourney.com/3b1a9073-297b-4592-8c0b-2889cddf245b/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'support', 'female'],
      },
      9: {
        title: 'The Dancer #9',
        link: '/gallery/the-dancer/9',
        date: new Date('11-05-2022').toISOString(),
        img: 'https://cdn.midjourney.com/8c1c0c1d-fc5c-4e1d-9b3a-6bdeb1c26d75/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'support', 'female'],
      },
      10: {
        title: 'The Dancer #10',
        link: '/gallery/the-dancer/10',
        date: new Date('11-05-2022').toISOString(),
        img: 'https://cdn.midjourney.com/545fdeac-f179-456e-9317-6050927c289e/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'support', 'female'],
      },
      11: {
        title: 'The Dancer #11',
        link: '/gallery/the-dancer/11',
        date: new Date('11-05-2022').toISOString(),
        img: 'https://cdn.midjourney.com/d91d792a-b025-438c-9d71-956a8a4c0476/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'support', 'female'],
      },
      12: {
        title: 'The Dancer #12',
        link: '/gallery/the-dancer/12',
        date: new Date('11-05-2022').toISOString(),
        img: 'https://cdn.midjourney.com/9a3a1f6c-80ee-4ed8-a48b-2c4bf27f5dbd/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'support', 'female'],
      },
    },
  },
  'the-barbarian': {
    title: 'The Barbarian',
    link: '/gallery/the-barbarian',
    date: new Date('11-04-2022').toISOString(),
    img: 'https://cdn.midjourney.com/4410e1eb-3cc0-4478-90d9-f250524c4609/grid_0.png',
    tags: ['fantasy', 'RPG', 'characters', 'warriors'],
    items: {
      1: {
        title: 'The Barbarian #1',
        link: '/gallery/the-barbarian/1',
        date: new Date('11-04-2022').toISOString(),
        img: 'https://cdn.midjourney.com/4410e1eb-3cc0-4478-90d9-f250524c4609/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'warriors', 'male'],
      },
      2: {
        title: 'The Barbarian #2',
        link: '/gallery/the-barbarian/2',
        date: new Date('11-04-2022').toISOString(),
        img: 'https://cdn.midjourney.com/f86b7eec-6714-40f9-9215-92024fc7cfd4/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'warriors', 'female'],
      },
      3: {
        title: 'The Barbarian #3',
        link: '/gallery/the-barbarian/3',
        date: new Date('11-04-2022').toISOString(),
        img: 'https://cdn.midjourney.com/5ab50e3c-bd29-414b-a514-d14cc6d2c045/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'warriors', 'male'],
      },
      4: {
        title: 'The Barbarian #4',
        link: '/gallery/the-barbarian/4',
        date: new Date('11-04-2022').toISOString(),
        img: 'https://cdn.midjourney.com/dae811d5-5eb9-443c-9065-2e0d48cf1afb/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'warriors', 'female'],
      },
      5: {
        title: 'The Barbarian #5',
        link: '/gallery/the-barbarian/5',
        date: new Date('11-04-2022').toISOString(),
        img: 'https://cdn.midjourney.com/127e8863-9538-4c5a-a620-f71ac552bb66/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'warriors', 'male'],
      },
      6: {
        title: 'The Barbarian #6',
        link: '/gallery/the-barbarian/6',
        date: new Date('11-04-2022').toISOString(),
        img: 'https://cdn.midjourney.com/5b595a97-13d6-40ed-b8bd-c2aaeb3d812f/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'warriors', 'female'],
      },
      7: {
        title: 'The Barbarian #7',
        link: '/gallery/the-barbarian/7',
        date: new Date('11-04-2022').toISOString(),
        img: 'https://cdn.midjourney.com/14612e6f-719e-4e9c-a6a4-f82c258fd003/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'warriors', 'male'],
      },
      8: {
        title: 'The Barbarian #8',
        link: '/gallery/the-barbarian/8',
        date: new Date('11-04-2022').toISOString(),
        img: 'https://cdn.midjourney.com/f07cdeef-f802-45c4-a9f3-11558951398b/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'warriors', 'female'],
      },
      9: {
        title: 'The Barbarian #9',
        link: '/gallery/the-barbarian/9',
        date: new Date('11-04-2022').toISOString(),
        img: 'https://cdn.midjourney.com/4b05403e-4507-428c-b58d-d36fcf71c541/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'warriors', 'male'],
      },
      10: {
        title: 'The Barbarian #10',
        link: '/gallery/the-barbarian/10',
        date: new Date('11-04-2022').toISOString(),
        img: 'https://cdn.midjourney.com/37f74423-5f0f-4bce-8af2-01f86b7a2ea6/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'warriors', 'female'],
      },
      11: {
        title: 'The Barbarian #11',
        link: '/gallery/the-barbarian/11',
        date: new Date('11-04-2022').toISOString(),
        img: 'https://cdn.midjourney.com/b573cd8d-a469-4fb4-a7e2-90856faffa87/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'warriors', 'male'],
      },
      12: {
        title: 'The Barbarian #12',
        link: '/gallery/the-barbarian/12',
        date: new Date('11-04-2022').toISOString(),
        img: 'https://cdn.midjourney.com/706f7843-8cce-45c1-83af-e2b5a5481883/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'warriors', 'female'],
      },
      13: {
        title: 'The Barbarian #13',
        link: '/gallery/the-barbarian/13',
        date: new Date('11-04-2022').toISOString(),
        img: 'https://cdn.midjourney.com/74d246b8-039e-46ec-914b-cac05cdeae64/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'warriors', 'male'],
      },
      14: {
        title: 'The Barbarian #14',
        link: '/gallery/the-barbarian/14',
        date: new Date('11-04-2022').toISOString(),
        img: 'https://cdn.midjourney.com/cce68ec3-4176-4ccd-aa48-8549e676afe7/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'warriors', 'female'],
      },
      15: {
        title: 'The Barbarian #15',
        link: '/gallery/the-barbarian/15',
        date: new Date('11-04-2022').toISOString(),
        img: 'https://cdn.midjourney.com/d7dcfc28-4937-4627-afe4-46319e9b55cd/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'warriors', 'male'],
      },
      16: {
        title: 'The Barbarian #16',
        link: '/gallery/the-barbarian/16',
        date: new Date('11-04-2022').toISOString(),
        img: 'https://cdn.midjourney.com/6437c87a-9c20-4cae-8386-5f43034e45b5/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'warriors', 'female'],
      },
      17: {
        title: 'The Barbarian #17',
        link: '/gallery/the-barbarian/17',
        date: new Date('11-04-2022').toISOString(),
        img: 'https://cdn.midjourney.com/7e62feee-76e9-4df4-9352-5e58deecc382/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'warriors', 'male'],
      },
      18: {
        title: 'The Barbarian #18',
        link: '/gallery/the-barbarian/18',
        date: new Date('11-04-2022').toISOString(),
        img: 'https://cdn.midjourney.com/d55174ac-c628-41e4-bb2d-3de911ee05e2/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'warriors', 'male'],
      },
    },
  },
  'the-artificer': {
    title: 'The Artificer',
    link: '/gallery/the-artificer',
    date: new Date('11-15-2022').toISOString(),
    img: 'https://cdn.midjourney.com/9195cd6f-b5f5-4fc3-af20-5a81d8011fd0/grid_0.png',
    tags: ['fantasy', 'RPG', 'characters', 'engineers'],
    items: {
      1: {
        title: 'The Artificer #1',
        link: '/gallery/the-artificer/1',
        date: new Date('11-15-2022').toISOString(),
        img: 'https://cdn.midjourney.com/9195cd6f-b5f5-4fc3-af20-5a81d8011fd0/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'engineers', 'animals'],
      },
      2: {
        title: 'The Artificer #2',
        link: '/gallery/the-artificer/2',
        date: new Date('11-15-2022').toISOString(),
        img: 'https://cdn.midjourney.com/fd222433-fb8b-4c10-922b-cecfbbce3bc7/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'engineers', 'male'],
      },
      3: {
        title: 'The Artificer #3',
        link: '/gallery/the-artificer/3',
        date: new Date('11-15-2022').toISOString(),
        img: 'https://cdn.midjourney.com/2c9398e7-da00-40c0-8d27-4817ebda4a1f/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'engineers', 'female'],
      },
      4: {
        title: 'The Artificer #4',
        link: '/gallery/the-artificer/4',
        date: new Date('11-15-2022').toISOString(),
        img: 'https://cdn.midjourney.com/e5083184-691a-47ee-a994-9eb90d051eb2/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'engineers', 'male'],
      },
      5: {
        title: 'The Artificer #5',
        link: '/gallery/the-artificer/5',
        date: new Date('11-15-2022').toISOString(),
        img: 'https://cdn.midjourney.com/99be53f0-9772-453c-bf6e-be825abeda06/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'engineers', 'female'],
      },
      6: {
        title: 'The Artificer #6',
        link: '/gallery/the-artificer/6',
        date: new Date('11-15-2022').toISOString(),
        img: 'https://cdn.midjourney.com/1ac9d60d-8971-4bda-b807-58a877bfe00d/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'engineers', 'male'],
      },
      7: {
        title: 'The Artificer #7',
        link: '/gallery/the-artificer/7',
        date: new Date('11-15-2022').toISOString(),
        img: 'https://cdn.midjourney.com/276f7da6-5f71-43a2-a575-d6c3ed2f1015/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'engineers', 'female'],
      },
      8: {
        title: 'The Artificer #8',
        link: '/gallery/the-artificer/8',
        date: new Date('11-15-2022').toISOString(),
        img: 'https://cdn.midjourney.com/675077a4-6378-452b-b0b7-2eab183452e6/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'engineers', 'male'],
      },
      9: {
        title: 'The Artificer #9',
        link: '/gallery/the-artificer/9',
        date: new Date('11-15-2022').toISOString(),
        img: 'https://cdn.midjourney.com/c8cc5316-3509-4393-ba6e-434808c36aa3/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'engineers', 'female'],
      },
      10: {
        title: 'The Artificer #10',
        link: '/gallery/the-artificer/10',
        date: new Date('11-15-2022').toISOString(),
        img: 'https://cdn.midjourney.com/a0f9503f-cc1f-41cd-a268-a45c9ee25ca7/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'engineers', 'male'],
      },
      11: {
        title: 'The Artificer #11',
        link: '/gallery/the-artificer/11',
        date: new Date('11-15-2022').toISOString(),
        img: 'https://cdn.midjourney.com/4c5d690d-8e19-4d17-88f5-1d2449d28247/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'engineers', 'female'],
      },
    },
  },
  'the-druid': {
    title: 'The Druid',
    link: '/gallery/the-druid',
    date: new Date('11-20-2022').toISOString(),
    img: 'https://cdn.midjourney.com/70c0dacc-d0d7-4594-9c7d-bbbab182fa9c/grid_0.png',
    tags: ['fantasy', 'RPG', 'characters', 'scholars'],
    items: {
      1: {
        title: 'The Druid #1',
        link: '/gallery/the-druid/1',
        date: new Date('11-20-2022').toISOString(),
        img: 'https://cdn.midjourney.com/70c0dacc-d0d7-4594-9c7d-bbbab182fa9c/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'male'],
      },
      2: {
        title: 'The Druid #2',
        link: '/gallery/the-druid/2',
        date: new Date('11-20-2022').toISOString(),
        img: 'https://cdn.midjourney.com/c7e45248-716d-4b42-b6ea-f56d6b352c36/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'female'],
      },
      3: {
        title: 'The Druid #3',
        link: '/gallery/the-druid/3',
        date: new Date('11-20-2022').toISOString(),
        img: 'https://cdn.midjourney.com/28c20408-f96a-49cc-91bc-4e9f92ea7ae0/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'male'],
      },
      4: {
        title: 'The Druid #4',
        link: '/gallery/the-druid/4',
        date: new Date('11-20-2022').toISOString(),
        img: 'https://cdn.midjourney.com/8aeefe3f-d0ad-4f25-8c93-1db0dc80095d/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'female'],
      },
      5: {
        title: 'The Druid #5',
        link: '/gallery/the-druid/5',
        date: new Date('11-20-2022').toISOString(),
        img: 'https://cdn.midjourney.com/63637159-1e94-44f5-92f0-e3bfd205e02f/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'male'],
      },
      6: {
        title: 'The Druid #6',
        link: '/gallery/the-druid/6',
        date: new Date('11-20-2022').toISOString(),
        img: 'https://cdn.midjourney.com/14733beb-0a9d-4d02-b47e-596376e13984/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'female'],
      },
      7: {
        title: 'The Druid #7',
        link: '/gallery/the-druid/7',
        date: new Date('11-20-2022').toISOString(),
        img: 'https://cdn.midjourney.com/3ddf1902-d4a4-4e43-9165-c48071da7063/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'male'],
      },
      8: {
        title: 'The Druid #8',
        link: '/gallery/the-druid/8',
        date: new Date('11-20-2022').toISOString(),
        img: 'https://cdn.midjourney.com/33727ed6-c541-4875-8fde-d40003f40fed/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'female'],
      },
      9: {
        title: 'The Druid #9',
        link: '/gallery/the-druid/9',
        date: new Date('11-20-2022').toISOString(),
        img: 'https://cdn.midjourney.com/7b702542-6ffa-48e7-9080-9047cb263c61/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'male'],
      },
      10: {
        title: 'The Druid #10',
        link: '/gallery/the-druid/10',
        date: new Date('11-20-2022').toISOString(),
        img: 'https://cdn.midjourney.com/30c3e64a-fab7-4f04-9fad-10165e6229dd/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'female'],
      },
      11: {
        title: 'The Druid #11',
        link: '/gallery/the-druid/11',
        date: new Date('11-20-2022').toISOString(),
        img: 'https://cdn.midjourney.com/c3c24022-ad1a-4cce-819b-7c947bf83c61/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'male'],
      },
      12: {
        title: 'The Druid #12',
        link: '/gallery/the-druid/12',
        date: new Date('11-20-2022').toISOString(),
        img: 'https://cdn.midjourney.com/b92302e7-cc02-43f3-8d54-91dde6fde484/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'female'],
      },
      13: {
        title: 'The Druid #13',
        link: '/gallery/the-druid/13',
        date: new Date('11-20-2022').toISOString(),
        img: 'https://cdn.midjourney.com/67429f9a-daa8-4042-8ab8-2b3a8110a452/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'male'],
      },
      14: {
        title: 'The Druid #14',
        link: '/gallery/the-druid/14',
        date: new Date('11-20-2022').toISOString(),
        img: 'https://cdn.midjourney.com/8aeefe3f-d0ad-4f25-8c93-1db0dc80095d/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'female'],
      },
      15: {
        title: 'The Druid #15',
        link: '/gallery/the-druid/15',
        date: new Date('11-20-2022').toISOString(),
        img: 'https://cdn.midjourney.com/007781d0-e942-43be-b07c-d58eb905f9c9/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'male'],
      },
      16: {
        title: 'The Druid #16',
        link: '/gallery/the-druid/16',
        date: new Date('11-20-2022').toISOString(),
        img: 'https://cdn.midjourney.com/e57a7b17-6ef8-4fd8-a538-a3fdc090e20c/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'female'],
      },
      17: {
        title: 'The Druid #17',
        link: '/gallery/the-druid/17',
        date: new Date('11-20-2022').toISOString(),
        img: 'https://cdn.midjourney.com/d21c33c6-bded-4645-bf18-b7f3b5935663/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'male'],
      },
      18: {
        title: 'The Druid #18',
        link: '/gallery/the-druid/18',
        date: new Date('11-20-2022').toISOString(),
        img: 'https://cdn.midjourney.com/15acb3cf-6909-4e2e-a0cb-66940baa6f89/grid_0.png',
        tags: ['fantasy', 'RPG', 'characters', 'scholars', 'female'],
      },
    },
  },
};
